name: farmy
description: New Flutter Application for Farmy
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_nav_bar: ^5.0.6
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.1
  flutter_progress_hud: ^2.0.2
  firebase_database: ^10.2.5
  fluttertoast: ^8.2.2
  flutter_session_manager: ^1.0.3
  image_picker: ^1.0.4
  flutter_speed_dial: ^7.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
